### ISSUE TITLE
Option to "Close" queue

### ISSUE THREAD

**Issue by michelleaw** [curriculagg/tracker#2]
- When a queue is closed, we don't want to accept any more tickets.
- Student's should probably see a message saying that the queue is closed and why, like: "There are a ton of people in line, so we have to close the queue :( We'll still probably be active on Piazza for a bit longer!" or "Office hours are closed. We will reopen tomorrow at 10 am!" or something.

**Comment by noahbkim** [comment]
This comes back around to staff access control. There's already a mechanism to close the queue, it just got Thanos'd when I removed everyone's access to queue deletion lmao. This can make a return pretty easily!
